spring:
  application:
    name: 05_Api_gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: demo-api
            uri: lb://DEMO-API
            predicates:
              - Path=/demo
          - id: test-api
            uri: lb://TEST-API
            predicates:
              - Path=/test
              
server:
  port: 3333
            
